### PR TITLE
Logging for large maps is prohibitively slow in firefox

### PR DESCRIPTION
**Pull request by sorenbs**

### CODE REVIEW

**Comment by mleveck** [comment]
How is this working for you otherwise (I merged the request)? I still
get some odd behavior (the map sometimes doesn't draw) depending on
the server I use.

On Mon, Feb 20, 2012 at 1:25 PM, sorenbs
reply@reply.github.com
wrote:

**Comment by sorenbs** [comment]
I haven't yet pinpointed the issue that causes the entire map to be blank until i reload the page. Otherwise it works pretty great. It even supports layers from Tiled :-)

**Comment by mleveck** [comment]
Can you try the dev version out now and see if you still need to reload?
Thanks
Matt

On Mon, Feb 20, 2012 at 2:38 PM, sorenbs
reply@reply.github.com
wrote:

**Comment by sorenbs** [comment]
That solves it. Great.

**Pull request merged**
