### PR TITLE
Property keys are now imported as components

### PR DESCRIPTION
**Pull request by funkjunky**
Property keys weren't being imported as components so I went and looked at the source, and it seemed you assumed some "components" key, instead of simply iterating over an object. Perhaps it was an old version of Tiled, or I misunderstood which properties the library imports.

Regardless, my change takes all the properties' keys and adds them as components.
It was enough to make my code work =P

Cheers,

Jason

### CODE REVIEW

**Comment by mleveck** [comment]
Jason,
   Thanks, it's actually been a long time since I've worked on this
project.  So, it may very well have been an old version of Tiled.  However,
could you please actually go ahead and edit the coffeescript source and
then compile, so that things don't get out of sync?
Thanks,
Matt

**Comment by funkjunky** [comment]
Wow, fast response, cool.
I'll make that change.

**Comment by funkjunky** [comment]
I had to learn a little coffee script, then not understand why "for k,v in object" was returning a numeric for loop rather than a for in loop. But once I eventually stopped being dumb and read the word "of" everything worked out. (I also had to npm -g coffee script =P)

**Comment by funkjunky** [comment]
I'm sorry, I misunderstood how your library worked. I didn't realize you imported components based on a field explicitly named "components". I'm going to close this.

I'm still working with it, so I may add things in the future, but I'm going to try my best to simply add them as separate components.

Sorry to bother you and have a superb day.

**Pull request closed without merging**
